sudo: required
services:
  - docker

before_install:
  - docker build -t harlesbayu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true harlesbayu/react-test npm run test -- --coverage

after_success:
  - docker build -t harlesbayu/multi-client ./client
  - docker build -t harlesbayu/multi-nginx ./nginx
  - docker build -t harlesbayu/multi-server ./server
  - docker build -t harlesbayu/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those image and push them to docker hub
  - docker push harlesbayu/multi-client
  - docker push harlesbayu/multi-nginx
  - docker push harlesbayu/multi-server
  - docker push harlesbayu/multi-worker